# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: fefezfezf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_34f86c0a37874edd890f8be04a9c0ff4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36137d0859f1453caf93e0b023573ddd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fefezfezf'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f6882c46e97454db3537c50d3318635 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_34f86c0a37874edd890f8be04a9c0ff4 }}/forsanta/hello-word:latest'
